function img=fuseImg(img1,imgpoly,mask,alpha)
%fuse a ploygon generated by getImgPoly using the mask and alpha rate.
%aplpha rate is in the range [0,1];
% sample: 
% First get a image with a red triangle
% [img1,~]=getImgPloy(50,100, [20,60,60],[20,20,40], [1,0,0]); 
% Then get a image wiht a green triangle, the corresponding mask
% [imgpoly,mask]=getImgPloy(50,100, [3,30,60],[30,10,40], [0,1,0]);
% Then fuse the second image to the first one with alpha=0.5
% img=fuseImg(img1,imgpoly,mask,0.5);
% now show the result
% imshow(img);
img=zeros(size(img1));
img(:,:,1)=img1(:,:,1).*(1-mask*alpha)+imgpoly(:,:,1).*mask*alpha;
img(:,:,2)=img1(:,:,2).*(1-mask*alpha)+imgpoly(:,:,2).*mask*alpha;
img(:,:,3)=img1(:,:,3).*(1-mask*alpha)+imgpoly(:,:,3).*mask*alpha;
